// Views for the real backend. Hidden buttons are convenience only; the server authorizes every call.
export function createBackendUI({gateway,access,launch,link,title,notice,escape,render,onResult}){
  let cache=new Map(),pending=new Set(),message='',editing=null,busy=false;
  const e=escape, money=p=>'₹'+(p/100).toLocaleString('en-IN'),stamp=s=>s?new Date(s).toLocaleString('en-IN'):'—';
  const route=r=>{location.hash='/'+r;};
  const admin=()=>access.snapshot.status==='authenticated'&&access.snapshot.user?.role==='admin';
  function clear(){cache=new Map();pending=new Set();editing=null;message='';}
  function get(key,action,payload={}){if(cache.has(key))return cache.get(key);if(!pending.has(key)){const current=cache;pending.add(key);gateway.call(action,payload).then(value=>{if(current!==cache)return;cache.set(key,value);}).catch(()=>{if(current===cache)cache.set(key,{error:true});}).finally(()=>{if(current===cache){pending.delete(key);render();}});}return null;}
  const loading=()=>notice('Loading secure records…');
  const failure=()=>notice('The backend could not load this information. Confirm Supabase configuration and sign in again.',true);
  const status=()=>message?`<p class="notice" role="status">${e(message)}</p>`:'';
  const field=(name,label,value='',type='text')=>`<div class="field"><label for="live-${name}">${e(label)}</label><input id="live-${name}" name="${name}" type="${type}" value="${e(value??'')}" ${type==='number'?'min="0" step="1"':''} ${busy?'disabled':''}></div>`;
  const select=(name,label,options,value)=>`<div class="field"><label for="live-${name}">${e(label)}</label><select id="live-${name}" name="${name}">${options.map(([v,l])=>`<option value="${e(v)}" ${String(value)===String(v)?'selected':''}>${e(l)}</option>`).join('')}</select></div>`;
  const note=()=>'<div class="field"><label>Reason / verification evidence<textarea name="reason" required minlength="5" maxlength="2000"></textarea></label></div>';
  const testCard=(t,c)=>{const s=c.subjects.find(s=>s.id===t.subject_id);return `<article class="card"><span class="pill ${t.access==='paid'?'premium':''}">${t.access==='paid'?'PREMIUM · SUBJECT ACCESS REQUIRED':'FREE · ₹0'}</span><h3 class="mt">${e(t.title)}</h3><p>${t.question_count} questions · ${Math.ceil(t.duration_seconds/60)} minutes</p>${t.access==='paid'?`<p>${money(s?.price_paise||0)} / ${s?.validity_months||3} calendar months</p>`:''}${link('test/'+t.id,'View test','btn secondary')}</article>`;};
  const locked=()=>title('PRIVATE ADMIN','Admin sign-in required','Only authorized Admin accounts can view or change content, student records and payments.')+notice(gateway.connected?'Log in with your Admin account. Authorization is checked by the backend on every request.':'Supabase is not configured. No Admin records or editing controls are available.',true)+link('login','Log in','btn');
  const adminTabs=[['exams','Exams'],['subjects','Subjects / Pricing'],['topics','Topics'],['tests','Tests'],['imports','HTML imports'],['payment_submissions','Payments'],['entitlements','Access'],['profiles','Students'],['admin_settings','Launch settings']];
  function adminView(id){
    if(!gateway.realBackend||!admin())return locked();
    const aliases={'overview':'exams','pricing':'subjects','orders':'payment_submissions','payments':'payment_submissions','access':'entitlements','students':'profiles','html-imports':'imports','launch-settings':'admin_settings','settings':'admin_settings'};
    const section=aliases[id]||id||'exams',entity=adminTabs.some(([v])=>v===section)?section:'exams';
    const records=get('admin:'+entity,'adminList',{entity});
    const header=title('PRIVATE ADMIN','Manage Sahoo ExamNexa','Changes are saved through authenticated server operations.')+`<nav class="chips admin-nav" aria-label="Admin sections">${adminTabs.map(([v,l])=>link('admin/'+v,l,'chip')).join('')}</nav>`+status();
    if(!records)return header+loading();if(records.error)return header+failure();
    if(entity==='imports')return header+importsView(records);
    if(entity==='payment_submissions')return header+`<div class="card"><h2>Manual UPI review</h2><p>Confirm the exact amount, payee and UTR against a received bank credit. A student claim alone is not proof.</p>${records.map(p=>`<article class="review-item"><h3>${e(p.subject_id)} · ${money(p.price_paise)}</h3><p>Order ${e(p.id)}<br>Student ${e(p.student_id)}<br>UTR ${e(p.utr||'Not submitted')} · ${e(p.status)}</p>${p.status==='pending_review'?`<form data-backend-form="review"><input type="hidden" name="orderId" value="${e(p.id)}">${note()}${select('decision','Decision',[['reject','Reject claim'],['approve','Approve received payment']],'reject')}<label><input type="checkbox" required> I have checked this decision against the bank/UPI record.</label><button class="btn mt">Save decision</button></form>`:''}</article>`).join('')||'<p>No submissions.</p>'}</div>`;
    if(entity==='entitlements')return header+`<div class="card"><h2>Grant / extend / revoke subject access</h2><form data-backend-form="access">${field('studentId','Student UUID')}${field('subjectId','Subject ID')}${select('operation','Operation',[['grant','Grant current subject term'],['extend','Extend by current subject term'],['revoke','Revoke immediately']],'grant')}${note()}<button class="btn">Save access change</button></form></div>`+table(records,entity,false);
    if(entity==='profiles')return header+table(records,entity,false);
    return header+table(records,entity,true)+editor(entity,editing?.entity===entity?editing.record:entity==='admin_settings'?records[0]:{});
  }
  function table(records,entity,editable){return `<section class="card mt"><h2>${e(adminTabs.find(([v])=>v===entity)?.[1]||entity)}</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Record</th><th>Details</th>${editable?'<th>Action</th>':''}</tr></thead><tbody>${records.map((r,i)=>`<tr><td>${e(r.name||r.title||r.display_name||r.student_id||'Settings')}<small>${e(r.id||r.subject_id||'')}</small></td><td>${e(r.role||r.access||r.price_paise!==undefined&&money(r.price_paise)||r.expires_at&&('Expires '+stamp(r.expires_at))||'')}${r.published!==undefined?` · ${r.published?'Published':'Hidden'}`:''}</td>${editable?`<td><button class="btn secondary small" data-backend-edit="${entity}" data-index="${i}">Edit</button></td>`:''}</tr>`).join('')}</tbody></table></div>${!records.length?'<p>No records yet.</p>':''}</section>`;}
  function editor(entity,r={}){
    let fields='';const pub=()=>select('published','Visibility',[[false,'Hidden / draft'],[true,'Published']],r.published??false);
    if(entity==='admin_settings')fields=select('telegram_required','Telegram requirement',[[true,'ON'],[false,'OFF']],r.telegram_required??true)+select('telegram_scope','Apply Telegram requirement to',[['all','All free mocks'],['selected','Selected free mocks']],r.telegram_scope||'all')+field('telegram_chat_id','Telegram channel ID (for example -100…) ',r.telegram_chat_id)+field('telegram_url','Telegram channel URL',r.telegram_url,'url')+field('youtube_name','YouTube channel name',r.youtube_name||'Sahoo ExamNexa')+field('youtube_cta','YouTube CTA text',r.youtube_cta||'Subscribe on YouTube')+field('youtube_url','YouTube URL · voluntary promotion only',r.youtube_url,'url')+field('youtube_videos_url','Free Study Videos / playlist URL',r.youtube_videos_url,'url')+field('upi_id','UPI ID',r.upi_id)+field('payee_name','Verified payee name',r.payee_name)+field('qr_url','UPI QR HTTPS image URL (Supabase public payment-assets bucket)',r.qr_url,'url');
    else{fields=field('id','Stable ID (lowercase / hyphens)',r.id)+field(entity==='tests'?'title':'name',entity==='tests'?'Test title':'Name',r.title||r.name);
      if(entity==='subjects')fields+=field('exam_ids','Exam IDs (comma-separated)',r.exam_ids?.join(', '))+field('price_paise','Price in paise (₹100 = 10000)',r.price_paise??0,'number')+field('validity_months','Validity in calendar months',r.validity_months??3,'number');
      if(['topics','tests'].includes(entity))fields+=field('subject_id','Subject ID',r.subject_id);
      if(entity==='tests')fields+=field('topic_id','Topic ID',r.topic_id)+select('access','Access type',[['free','FREE'],['paid','PREMIUM']],r.access||'free')+field('duration_seconds','Duration in seconds',r.duration_seconds??600,'number')+select('telegram_required','Telegram in selected-free-mocks mode (ignored for paid)',[[false,'Not selected'],[true,'Require membership']],r.telegram_required??false);fields+=pub();
    }
    return `<section class="card mt"><h2>${r.id?'Edit record':'Create record'}</h2><form data-backend-form="save" data-entity="${entity}"><div class="form-grid">${fields}</div><p>Existing IDs retain their identity. Tests need both import-verification passes before publication.</p><button class="btn">Save to database</button></form></section>`;
  }
  function importsView(records){const detail=cache.get('importDetail');return `<section class="card"><h2>Import one HTML test</h2><p>The original HTML and all records are stored privately. Only 🟢 is removed from student-facing question text. No question is added, dropped, merged or renumbered. An existing import cannot be overwritten.</p><form data-backend-form="import">${field('testId','Existing draft test ID')}${field('expectedCount','Exact source question count','','number')}<div class="field"><label>HTML file<input type="file" name="html" accept=".html,.htm" required></label></div><button class="btn">Import and run structural pass</button></form></section><section class="card mt"><h2>Verification queue</h2>${records.map(r=>`<article class="review-item"><h3>${e(r.test_id)}</h3><p>Source ${r.source_count} · Imported ${r.imported_count} · Added ${r.added} · Removed ${r.removed}<br>Pass 1: ${r.pass1?'passed':'issues'} · Pass 2: ${r.pass2?'approved':'pending'}</p><button class="btn secondary" data-backend-import="${e(r.id)}">Review every question and finding</button></article>`).join('')||'<p>No imports.</p>'}</section>${detail?`<section class="card mt"><h2>Full content review</h2><p>${detail.imported_count} questions · source hash ${e(detail.source_sha256)}</p><pre class="backend-json">${e(JSON.stringify(detail.issues,null,2))}</pre>${detail.working.map(q=>`<article class="review-item"><h3>${q.number}. ${e(q.text)}</h3><ol type="A">${q.options.map(o=>`<li>${e(o.text)}${o.id===q.correctOptionId?' — marked answer':''}</li>`).join('')}</ol><p>${e(q.explanation)}</p><p>Tags: ${q.tags.map(e).join(' · ')}</p></article>`).join('')}<form data-backend-form="verify-import"><input type="hidden" name="importId" value="${e(detail.id)}"><label><input type="checkbox" required> I reviewed every question, answer mapping, explanation and source tag. There are no unresolved blocking findings.</label>${note()}<button class="btn mt" ${!detail.pass1?'disabled':''}>Approve content pass</button></form></section>`:''}`;}
  function view(page,id,params){
    if(page==='admin')return adminView(id);
    if(!gateway.realBackend)return null;
    if(['login','register','about','help','privacy','syllabus','pyqs'].includes(page))return null;
    if(page==='account')return launch.account()+status()+`<section class="card mt"><h2>Update your profile</h2><form data-backend-form="profile">${field('displayName','Name',access.snapshot.user?.displayName)}<button class="btn" ${access.snapshot.status!=='authenticated'?'disabled':''}>Save profile</button></form></section>`;
    if(['orders','dashboard','results'].includes(page)){
      if(access.snapshot.status!=='authenticated')return title('MY ACCOUNT','Log in to continue','Your payments, access and saved results are private.')+link('login','Log in','btn');
      const orders=get('orders','orders'),results=get('results','results');if(!orders||!results)return loading();if(orders.error||results.error)return failure();
      return title('YOUR LEARNING','My subjects and results','Your saved account records.')+status()+`<div class="grid cols-2">${orders.entitlements.map(r=>`<article class="card"><h2>${e(r.subject_id)}</h2><p>${r.revoked_at?'Revoked':Date.parse(r.expires_at)>Date.now()?'Active until '+stamp(r.expires_at):'Expired'}</p>${link('subject/'+r.subject_id,'Open subject','btn secondary')} ${link('purchase/'+r.subject_id,'Renew Access','text-link')}</article>`).join('')}</div><section class="card mt"><h2>Payment submissions</h2>${orders.orders.map(r=>`<p>${e(r.subject_id)} · ${money(r.price_paise)} · ${e(r.status)} ${r.status==='awaiting_payment'?link('purchase/'+r.subject_id,'Complete payment','text-link'):''}${r.review_note?'<br>'+e(r.review_note):''}</p>`).join('')||'<p>No payments.</p>'}</section><section class="card mt"><h2>Saved attempts</h2>${results.map(r=>`<p>${e(r.testId)} · ${stamp(r.startedAt)} · ${r.submittedAt?`${r.score}/${r.total} <button class="btn secondary small" data-backend-result="${e(r.id)}">Review result</button>`:`Not submitted <button class="btn secondary small" data-backend-finalize="${e(r.id)}">Finalize saved answers</button>`}</p>`).join('')||'<p>No attempts yet.</p>'}</section>`;
    }
    const c=get('catalog','catalog');if(!c)return loading();if(c.error)return failure();
    if(['home','exams'].includes(page))return title('SAHOO EXAMNEXA','Topic-wise Mock Tests','Choose your exam → subject → topic → FREE / PREMIUM test.')+`<div class="grid cols-3">${c.exams.map(r=>`<article class="card"><h2>${e(r.name)}</h2>${link('exam/'+r.id,'Choose exam','btn secondary')}</article>`).join('')||'<section class="card"><h2>Tests are being prepared</h2><p>Published exams will appear here after Admin reviews the content.</p></section>'}</div>`;
    if(['exam','subjects','pricing'].includes(page))return title('TOPIC-WISE MOCK TESTS','Choose your subject','Subject access starts after manual payment approval.')+`<div class="grid cols-3">${c.subjects.filter(s=>page!=='exam'||s.exam_ids.includes(id)).map(s=>`<article class="card"><h2>${e(s.name)}</h2><p>${money(s.price_paise)} / ${s.validity_months} calendar months</p>${link('subject/'+s.id,'Explore topics','btn secondary')}</article>`).join('')||'<p>No published subjects yet.</p>'}</div>`;
    if(page==='subject'){const s=c.subjects.find(s=>s.id===id);if(!s)return notice('Subject unavailable');return title('SUBJECT → TOPIC',e(s.name),`${money(s.price_paise)} / ${s.validity_months} calendar months`)+link('purchase/'+s.id,'Buy / renew subject access','btn')+`<div class="grid cols-3 mt">${c.topics.filter(t=>t.subject_id===id).map(t=>`<article class="card"><h2>${e(t.name)}</h2>${link('topic/'+t.id,'View tests','btn secondary')}</article>`).join('')}</div>`;}
    if(['topic','tests'].includes(page)){const t=c.topics.find(t=>t.id===id)||c.topics.find(t=>t.subject_id===id&&t.name===params.get('name'));return title('TOPIC-WISE MOCK TESTS',e(t?.name||'Free and premium tests'),'Choose a test to review the access requirements.')+`<div class="grid cols-3">${c.tests.filter(x=>page==='tests'||x.topic_id===t?.id).map(t=>testCard(t,c)).join('')||'<p>No published tests yet.</p>'}</div>`;}
    if(page==='test'){
      const t=c.tests.find(t=>t.id===id);if(!t)return notice('Test unavailable');
      let gate=launch.freeGate(t,params);
      if(t.access==='paid'){const s=c.subjects.find(s=>s.id===t.subject_id);const a=access.snapshot.status==='authenticated'?get('access:'+s.id,'access',{subjectId:s.id}):null;gate=launch.premiumStatus(a)+link('purchase/'+s.id,`Buy / renew · ${money(s.price_paise)} / ${s.validity_months} months`,'btn secondary')+` <button class="btn" data-start="${e(id)}" ${a?.state==='active'?'':'disabled'}>Start Premium Mock</button>`+(access.snapshot.status!=='authenticated'?link('login?next=test/'+id,'Log in','btn secondary'):'');}
      return title('TOPIC-WISE MOCK',e(t.title),`${t.question_count} questions · ${Math.ceil(t.duration_seconds/60)} minutes · +1 / 0 marking`)+status()+gate;
    }
    if(page==='purchase'){
      const s=c.subjects.find(s=>s.id===id);if(!s)return notice('Subject unavailable');
      const checkout=cache.get('checkout:'+id);return title('BUY SUBJECT',e(s.name),`${money(s.price_paise)} / ${s.validity_months} calendar months. Activation follows Admin approval.`)+status()+`<section class="card"><h2>UPI → UTR → manual approval</h2>${access.snapshot.status!=='authenticated'?link('login?next=purchase/'+id,'Log in to purchase','btn'):`<button class="btn" data-backend-buy="${e(id)}">Create / view payment order</button>`}${checkout?`<div class="mt"><p>Pay exactly <strong>${money(checkout.order.price_paise)}</strong> to <strong>${e(checkout.payeeName)}</strong><br>UPI ID: ${e(checkout.upiId)}</p><img class="payment-qr" src="${e(checkout.qrUrl)}" alt="UPI payment QR"><p>Order: ${e(checkout.order.id)} · ${e(checkout.order.status)}<br>Never share a PIN or OTP.</p>${checkout.order.status==='awaiting_payment'?`<form data-backend-form="payment"><input type="hidden" name="orderId" value="${e(checkout.order.id)}">${field('utr','UTR / transaction reference')}<button class="btn">Submit UTR for Admin verification</button></form>`:'<p>Payment submitted. Access stays locked until Admin confirms receipt.</p>'}</div>`:''}</section>`;
    }
    return null;
  }
  async function perform(work){if(busy)return;busy=true;message='Saving…';render();try{await work();message='Saved successfully.';}catch(err){message=err.message||'Request failed. Please try again.';}finally{busy=false;render();}}
  document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;
    if(b.dataset.backendEdit){editing={entity:b.dataset.backendEdit,record:cache.get('admin:'+b.dataset.backendEdit)[Number(b.dataset.index)]};render();return;}
    if(b.dataset.backendBuy)perform(async()=>{const current=cache,data=await gateway.call('createOrder',{subjectId:b.dataset.backendBuy,idempotencyKey:crypto.randomUUID()});if(current===cache)cache.set('checkout:'+b.dataset.backendBuy,data);});
    if(b.dataset.backendImport)perform(async()=>{const current=cache,data=await gateway.call('adminImportDetail',{importId:b.dataset.backendImport});if(current===cache)cache.set('importDetail',data);});
    if(b.dataset.backendResult)perform(async()=>{const current=cache,data=await gateway.call('result',{attemptId:b.dataset.backendResult});if(current===cache)await onResult(data);});
    if(b.dataset.backendFinalize)perform(async()=>{const current=cache,data=await gateway.call('submitAttempt',{attemptId:b.dataset.backendFinalize});if(current===cache){await onResult(data);cache.delete('results');}});
  });
  document.addEventListener('submit',event=>{const form=event.target,kind=form.dataset.backendForm;if(!kind)return;event.preventDefault();const data=Object.fromEntries(new FormData(form));perform(async()=>{
    if(kind==='save'){const record={...data};for(const name of ['published','telegram_required'])if(name in record)record[name]=record[name]==='true';for(const name of ['price_paise','validity_months','duration_seconds'])if(name in record)record[name]=Number(record[name]);if(record.exam_ids!==undefined)record.exam_ids=record.exam_ids.split(',').map(s=>s.trim()).filter(Boolean);await gateway.call('adminSave',{entity:form.dataset.entity,record});}
    if(kind==='review')await gateway.call('adminReviewPayment',data);
    if(kind==='access')await gateway.call('adminAccess',data);
    if(kind==='payment')await gateway.call('submitPayment',data.utr?{orderId:data.orderId,utr:data.utr}:{});
    if(kind==='profile'){await gateway.call('updateProfile',data);await access.restore();}
    if(kind==='import'){if(!(data.html instanceof File)||data.html.size>1024*1024)throw new Error('Choose one HTML file up to 1 MB.');await gateway.call('adminImportHtml',{testId:data.testId,html:await data.html.text(),expectedCount:Number(data.expectedCount)});}
    if(kind==='verify-import')await gateway.call('adminVerifyContent',{...data,decision:'approve'});
    clear();await access.restore();
  });});
  return {view,clear,getTest:id=>cache.get('catalog')?.tests.find(t=>t.id===id)};
}
