import {subjectPlans,premiumTests,getPlan,money,orderStatuses} from './commerce.js';

// Presentation only: no sessions, purchases, approvals or entitlement decisions.
export function createCommerceViews({icon,link,title,notice,empty,escape,exams,getLaunchPolicy=()=>({}),youtubePromotion=()=>''}) {
  const context=params=>exams.find(e=>e.id===params.get('exam'));
  const contextTrail=params=>{const e=context(params);return e?'<div class="context-trail">'+link('exam/'+e.id,e.name,'text-link')+'<span> / Subject / Topic / Mock test</span></div>':'';};
  const suffix=params=>context(params)?'?exam='+context(params).id:'';
  const steps=()=>'<ol class="purchase-steps">'+[
    ['Choose a subject','All included topic-wise mock tests in one three-month subscription.'],
    ['Sign in & pay by UPI','Use the ExamNexa QR, verified payee and exact order amount.'],
    ['Submit your UTR','Your subject stays locked during manual payment review.'],
    ['Study for three months','Access starts on server activation after payment approval.']
  ].map(([h,p],i)=>'<li><span>0'+(i+1)+'</span><div><b>'+h+'</b><p>'+p+'</p></div></li>').join('')+'</ol>';
  const planPrice=p=>'<strong class="subject-price">'+money(p.pricePaise)+'</strong><span class="price-term"> / 3 months</span><p class="price-disclaimer">Illustrative price · Purchases not open</p>';
  function subjectCard(p,exam='') {return '<article class="card subject-product"><div class="card-top"><div class="icon-box '+p.color+'">'+icon(p.icon)+'</div><span class="pill premium">'+icon('lock')+' PREMIUM</span></div><h3>'+p.name+'</h3><p>'+p.topics.length+' topics · Topic-wise mock tests</p><div class="topic-teaser">'+p.topics.slice(0,3).map(t=>'<span>'+escape(t)+'</span>').join('')+'</div><div class="mt">'+planPrice(p)+'</div>'+link('subject/'+p.id+(exam?'?exam='+exam:''),'Explore subject','btn secondary wide','arrow')+'</article>';}
  function subjectStore(params=new URLSearchParams()) {const exam=context(params)?.id||'';return contextTrail(params)+title('TOPIC-WISE MOCK TESTS','One subject. A focused path forward.','Build your preparation topic by topic. One subject subscription includes all its available premium mock tests for three months.')+'<div class="store-banner"><div><span class="pill">FREE</span><h2>Start with a little confidence.</h2><p>Explore FREE samples before choosing your subject. Registration and access verification are required to start.</p></div>'+link('tests?access=free','Try free samples','btn','arrow')+'</div>'+notice('Preview catalog: subject mappings, prices and planned test specifications are illustrative. Final exam coverage and content must be reviewed before sale.')+'<div class="grid cols-3">'+subjectPlans.map(p=>subjectCard(p,exam)).join('')+'</div>';}
  function subjectDetail(id,params=new URLSearchParams()) {const p=getPlan(id);if(!p)return null;const exam=context(params)?.id||'';return contextTrail(params)+link('subjects'+(exam?'?exam='+exam:''),'← Subjects','text-link')+title('SUBJECT → TOPICS → MOCK TESTS',p.name+' – 3 Months Access','All included '+p.name+' topic-wise mock tests. One subject purchase, a structured way to practise.')+'<div class="split"><section class="card"><span class="pill premium">'+icon('lock')+' SUBJECT ACCESS LOCKED</span><h2 class="mt">Make each topic count.</h2><p>Choose a topic below, then explore its mock tests. Access lasts three calendar months from activation, with purchase, activation and expiry dates saved to your account.</p><ul class="feature-list"><li>'+icon('check')+'All included topic-wise tests in this subject</li><li>'+icon('check')+'Planned saved scores, subject analysis and answer review</li><li>'+icon('check')+'Renew at the current subject price after expiry</li></ul>'+socialStrip()+'</section>'+summary(p,params)+'</div><section class="section">'+ '<div class="section-head"><div><h2>Explore the topics</h2><p>Topic-wise mock tests are the core of your preparation.</p></div></div><div class="grid cols-3">'+p.topics.map((t,i)=>'<article class="card"><span class="eyebrow">TOPIC '+String(i+1).padStart(2,'0')+'</span><h3>'+escape(t)+'</h3><p>1 planned topic-wise mock · Premium</p>'+link('topic/'+p.id+'?name='+encodeURIComponent(t)+(exam?'&exam='+exam:''),'View topic tests','text-link','arrow')+'</article>').join('')+'</div></section>'+reviews(id);}
  function summary(p,params=new URLSearchParams()){return '<aside class="card purchase-summary"><span class="pill premium">'+icon('lock')+' 3-MONTH SUBJECT ACCESS</span><h2 class="mt">'+p.name+'</h2>'+planPrice(p)+'<div class="locked-strip">'+icon('lock')+' Locked · Not activated</div><p>Includes '+p.topics.length+' planned topics. No original HTML downloads.</p>'+link('purchase/'+p.id+suffix(params),'View purchase steps','btn wide','arrow')+'<p class="price-disclaimer">A subject subscription, not an individual test or file purchase. Final price and terms need approval.</p></aside>';}
  function topicTests(subjectId,topic,params=new URLSearchParams(),freeSample=null){
    const p=getPlan(subjectId);if(!p || !p.topics.includes(topic))return '';
    const sample=freeSample ? '<article class="card"><span class="pill">FREE SAMPLE</span><h3 class="mt">'+escape(freeSample.title)+'</h3><p>'+freeSample.ids.length+' sample questions · '+freeSample.minutes+' min · ₹0</p><p>No payment needed. Registration and channel verification are required.</p>'+link('test/'+freeSample.id+suffix(params),'Try free topic sample','btn secondary','arrow')+'</article>' : '';
    return '<section class="section"><h2>Topic-wise mock tests</h2><div class="grid cols-2">'+sample+premiumTests.filter(t=>t.planId===subjectId && t.topic===topic).map(t=>'<article class="card"><span class="pill premium">'+icon('lock')+' PREMIUM · LOCKED</span><h3 class="mt">'+escape(t.title)+'</h3><p>'+t.questionCount+' planned questions · '+t.minutes+' min default timer</p><p>Included with '+p.name+' – 3 Months Access · '+money(p.pricePaise)+' illustrative</p>'+link('test/'+t.id+suffix(params),'View test details','btn secondary','arrow')+'</article>').join('')+'</div>'+(freeSample?'':'<p class="mt">No free sample for this topic yet. '+link('tests?access=free','Try other free samples','text-link')+'</p>')+'</section>';
  }
  function premiumDetail(id,params=new URLSearchParams()){const t=premiumTests.find(t=>t.id===id);if(!t)return null;const p=getPlan(t.planId);return contextTrail(params)+link('subject/'+p.id+suffix(params),'← '+p.name,'text-link')+title('TOPIC-WISE MOCK · PREMIUM',t.title,'Part of '+p.name+' – 3 Months Access. This planned test remains locked.')+'<div class="split"><section class="card"><span class="pill premium">'+icon('lock')+' LOCKED</span><h2 class="mt">Practise the topic. Build the foundation.</h2><p>'+t.desc+'</p><div class="grid cols-2"><div><span class="stat-value">'+t.questionCount+'</span><span class="stat-label">Planned questions</span></div><div><span class="stat-value">'+t.minutes+' min</span><span class="stat-label">Default: questions ÷ 4</span></div></div><p class="mt">Purchased tests will use the same Sahoo ExamNexa CBT interface. Answers and explanations appear only after final submission.</p>'+link('tests?access=free','Experience a free sample','btn secondary')+'</section>'+summary(p,params)+'</div>'+notice('Only product metadata is included here. No premium question data, answer keys or original HTML files are served. Secure subject entitlement checks and server delivery are not yet connected.');}
  function purchase(id,params=new URLSearchParams()){const p=getPlan(id);if(!p)return null;return contextTrail(params)+link('subject/'+id+suffix(params),'← Subject details','text-link')+title('BUY SUBJECT ACCESS',p.name+' – 3 Months Access','UPI payment → UTR submission → manual approval → three-month subject activation.')+notice('Purchases are not open. No UPI QR is configured. Do not send money or enter a real transaction ID in this preview.',true)+'<div class="split"><section class="card"><h2>1. Your student account</h2><p>Secure sign-in is required to create a subject order.</p>'+link('login','View login','btn secondary')+' '+link('register','View registration','text-link')+'<h2 class="mt">2. Pay by UPI</h2><div class="qr-placeholder">'+icon('lock')+'<strong>ExamNexa UPI QR</strong><span>Awaiting Admin-configured payment details</span></div><p>The future checkout will show the verified payee, UPI ID, exact payable amount, subject and order reference. Never share a UPI PIN or OTP.</p><div class="field"><label for="checkout-coupon">Coupon code</label><input id="checkout-coupon" disabled placeholder="Server-validated coupons will apply here"></div><h2 class="mt">3. Submit your payment reference</h2><form id="payment-reference-form"><div class="field"><label for="payment-order">Order reference</label><input id="payment-order" disabled placeholder="Created by the server"></div><div class="field"><label for="payment-utr">UTR / transaction ID</label><input id="payment-utr" disabled placeholder="Reference from your UPI app"></div><div class="field"><label for="payment-date">Payment date</label><input id="payment-date" type="date" disabled></div><button class="btn wide" type="button" disabled>Submit for verification · Unavailable</button></form><p class="mt">A submitted UTR is a claim, not proof. Access stays locked until an authorized admin matches the payment to an actual credit.</p><h2 class="mt">4. Activation & renewal</h2><p>The server records purchase, activation and expiry dates. New access lasts three calendar months from activation. Expired access locks automatically and renewal uses the current Admin-configured subject price.</p></section>'+summary(p,params)+'</div>'+orderGuide();}
  function orderGuide(){return '<details class="mt"><summary>How payment review will work</summary><div class="details-body status-guide">'+orderStatuses.map(s=>'<div><span class="pill neutral">'+s.label+'</span><p>'+s.description+'</p></div>').join('')+'</div></details>';}
  function orders(){return title('MY SUBJECTS & PURCHASES','Your learning, all in one place.','Subject access, renewal dates, payment updates and saved attempts belong to your secure student account.')+'<div class="account-banner"><div>'+icon('lock')+'<strong>No student account connected</strong><p>No orders, expiry dates or access grants are simulated.</p></div>'+link('login','View login','btn secondary')+'</div><div class="chips mt">'+[['tests','My subjects'],['orders','Orders & payment status'],['results','Saved attempts']].map(([v,l],i)=>'<button class="chip '+(i===0?'active':'')+'" data-order-tab="'+v+'" aria-pressed="'+(i===0)+'">'+l+'</button>').join('')+'</div><div id="purchase-tab-content" class="mt">'+orderTab('tests')+'</div><details class="mt"><summary>Subject access states · Interface guide</summary><div class="details-body grid cols-3"><div><span class="pill">Active</span><p>Purchase date, activation date and expiry are provided by the server.</p><button class="btn secondary" disabled>Open subject</button></div><div><span class="pill orange">Expired · Locked</span><p>Expiry is enforced by the server on every premium request. Renew at the current price.</p><button class="btn secondary" disabled>Renew Access</button></div><div><span class="pill neutral">Revoked · Locked</span><p>Authorized access changes include a reason and audit record.</p><button class="btn secondary" disabled>Ask Admin</button></div></div></details>'+orderGuide();}
  function orderTab(tab){return ({tests:empty('Your purchased subjects will live here','Active subjects will show purchase, activation and expiry dates. Expired subjects will show Renew Access at the current price.',link('subjects','Explore subjects','btn')),orders:empty('No order history connected','Order reference, subject, payment amount, UTR review and rejection reasons require secure sign-in.',link('subjects','Browse subjects','btn secondary')),results:empty('Saved attempts need a student account','Future results will be stored securely. Free-sample results currently last for this open page session.',link('dashboard','View guest session','btn secondary'))})[tab];}
  function account(){return title('STUDENT ACCOUNT','A home for your preparation.','Purchased subjects, subscription dates, saved results and private support in one future account.')+notice('Guest preview: no signed-in session or account data is simulated.')+'<div class="grid cols-2"><section class="card"><h2>Your profile</h2><div class="field"><label for="account-name">Name</label><input id="account-name" placeholder="Available after sign-in" disabled></div><div class="field"><label for="account-email">Email</label><input id="account-email" disabled placeholder="Available after sign-in"></div><button class="btn secondary" disabled>Save profile</button></section><section class="card"><h2>Your learning space</h2><ul class="feature-list"><li>'+icon('check')+'Subject subscriptions and renewals</li><li>'+icon('check')+'Payment updates and saved results</li><li>'+icon('check')+'Private Ask ExamNexa AI / Admin support</li></ul>'+link('orders','My subjects & orders','btn')+' '+link('support','Ask ExamNexa AI','text-link','arrow')+'</section></div>';}
  function adminOrders(){return '<section class="card"><h2>Subject orders & purchases</h2><p>Server records link student, subject, price snapshot, discounts, payment claims and three-month access.</p><div class="toolbar"><label for="admin-order-status">Status</label><select id="admin-order-status"><option>All statuses</option>'+orderStatuses.map(s=>'<option>'+s.label+'</option>').join('')+'</select><button class="btn secondary" disabled>Export private orders</button></div>'+empty('No order database connected','Order IDs, students, amounts and UTRs are private. This public UI preview cannot list or modify them.')+'</section>'+orderGuide();}
  function adminPayments(){return '<div class="grid cols-2"><section class="card"><span class="pill orange">MANUAL UPI VERIFICATION</span><h2 class="mt">Verify receipt. Then activate.</h2><p>Match the submitted UTR, payee, amount and date against an actual ExamNexa bank/UPI credit. Check that the credit has not already funded another order.</p>'+empty('No payment claims connected','No fake transactions or client-side approvals are generated.')+'<div class="field mt"><label for="review-order">Pending subject order</label><input id="review-order" disabled placeholder="Select an authorized pending order"></div><div class="field"><label for="review-utr">Submitted UTR</label><input id="review-utr" disabled placeholder="Unverified student claim"></div><div class="field"><label for="review-note">Review note / rejection reason</label><textarea id="review-note" disabled></textarea></div><button class="btn" disabled>Approve & activate subject</button> <button class="btn secondary" disabled>Reject claim</button>'+notice('Approval and three-month subject activation must occur atomically on the server, with reviewer identity and an audit record.')+'</section><section class="card"><h2>ExamNexa UPI configuration</h2><div class="field"><label for="payee-name">Verified payee name</label><input id="payee-name" disabled placeholder="Awaiting ExamNexa details"></div><div class="field"><label for="payee-upi">ExamNexa UPI ID</label><input id="payee-upi" disabled placeholder="Not configured"></div><div class="field"><label for="payee-qr">UPI QR image</label><input id="payee-qr" type="file" accept="image/png,image/jpeg" disabled></div><button class="btn secondary" disabled>Save payment details</button><p class="mt">Changes require privileged server authorization and an audit record. No real payment destination has been supplied.</p></section></div>';}
  function socialStrip(){return youtubePromotion(true);}
  function reviews(id){return '<section class="section card"><div class="section-head"><div><h2>Student ratings & reviews</h2><p>Reviews for '+(getPlan(id)?.name||'this subject')+'</p></div><span class="pill neutral">No ratings yet</span></div><p>No reviews have been collected. Verified Purchase labels will be based on server-confirmed subject purchases.</p><div class="form-grid"><div class="field"><label for="review-stars">Your rating</label><select id="review-stars" disabled><option>Choose 1–5 stars after sign-in</option></select></div><div class="field"><label for="review-comment">Your review</label><textarea id="review-comment" disabled placeholder="Share your experience after secure setup"></textarea></div></div><button class="btn secondary" disabled>Submit review</button></section>';}
  function pricing(){return subjectStore();}
  return {subjectCard,subjectStore,subjectDetail,topicTests,premiumDetail,purchase,orders,orderTab,account,adminOrders,adminPayments,pricing,socialStrip,reviews,steps};
}

