import {safeChannelUrl,subjectAccessLabel} from './launch-access.js';

export function createLaunchViews({link,title,notice,escape,access,connected}){
  const destination=params=>{const next=params.get('next')||'account';return /^(test|purchase)\/[a-z0-9-]+(?:\?exam=[a-z0-9-]+)?$/.test(next)?next:'account';};
  const authLink=(route,next,label)=>link(route+'?next='+encodeURIComponent(next),label,'btn secondary');
  const statusMessage=()=>`<p role="status" class="notice">${escape(access.snapshot.message||(connected?'Use your confirmed email account. Test access is checked by the server.':'Sign-in and access verification require the backend/Supabase integration. No access has been granted.'))}</p>`;
  function youtubePromotion(compact=false){
    const p=access.snapshot.policy,channel=safeChannelUrl(p.youtubeChannelUrl,'youtube'),videos=safeChannelUrl(p.youtubeVideosUrl,'youtubeVideo');
    const button=(url,label,cls)=>url?`<a class="btn ${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)}</a>`:`<button class="btn ${cls}" disabled>${escape(label)}</button>`;
    return `<aside class="youtube-promotion ${compact?'youtube-compact':'card'}" aria-label="Optional YouTube updates"><div class="youtube-copy"><span class="eyebrow"><span aria-hidden="true">▶</span> FREE STUDY VIDEOS · YOUTUBE</span>${compact?'':`<h2>Learn with ${escape(p.youtubeChannelName||'Sahoo ExamNexa')}</h2>`}<p>Subscribe and turn on the bell for new mock-test updates.</p></div><div class="youtube-actions">${button(channel,p.youtubeCtaText||'Subscribe on YouTube','youtube-button')}${button(videos,'Watch Free Study Videos','secondary')}</div><small>Voluntary: subscribing and bell settings never affect test access.${!channel||!videos?' Links awaiting Admin configuration.':''}</small></aside>`;
  }
  function freeGate(test,params){
    const s=access.snapshot,p=s.policy,e=s.eligibility?.testId===test.id?s.eligibility:null;
    const next='test/'+test.id+(params.get('exam')?'?exam='+params.get('exam'):'');
    const check=e?.checks.find(c=>c.provider==='telegram'),required=check?.required??(p.telegramRequired&&(p.telegramScope!=='selected'||test.telegram_required===true||p.telegramTestIds.includes(test.id))),url=safeChannelUrl(p.telegramChannelUrl,'telegram');
    const linked=check?.linked===true||['verified','not_member'].includes(check?.status);
    const text=!required?'Not required for this free mock':check?.status==='verified'?'Verified':check?.status==='not_member'?'Not verified — Join Sahoo ExamNexa Telegram':check?.status==='unavailable'?'Telegram verification temporarily unavailable. Please retry.':check?.status==='not_linked'?'Connect Telegram to continue.':'Connect your account, join the channel, then verify membership.';
    const disabled=!connected||s.status!=='authenticated'||s.busy;
    const telegram=required?`<div class="access-step"><h3>2. Telegram membership</h3><p role="status">${text}</p><div class="chips">${!linked?`<button class="btn secondary" data-social-link="telegram" ${disabled?'disabled':''}>Connect Telegram</button>`:'<span class="pill neutral">Telegram connected</span>'}${url?`<a class="btn secondary" href="${escape(url)}" target="_blank" rel="noopener noreferrer">Join Sahoo ExamNexa Telegram</a>`:'<button class="btn secondary" disabled>Join Sahoo ExamNexa Telegram</button>'}</div>${!url?'<p class="muted">Telegram channel link awaiting Admin configuration.</p>':''}</div>`:`<p class="notice">${text}. Log in and start when ready.</p>`;
    return `<section class="card account-before-mock"><span class="pill">FREE · ₹0</span><h2 class="mt">1. Student account</h2>${s.status==='authenticated'?`<p>Signed in as ${escape(s.user.displayName||s.user.email)}</p>`:`<p>Register or log in before attempting any mock.</p><div class="chips">${authLink('register',next,'Register')}${authLink('login',next,'Log in')}</div>`}</section>${youtubePromotion()}<section class="card access-gate" aria-label="Free mock access requirements"><h2>Start your free topic-wise mock</h2>${telegram}${statusMessage()}<div class="chips">${required?`<button class="btn secondary" data-verify-free="${test.id}" ${disabled?'disabled':''}>${e?'Verify Again':'Verify Membership'}</button>`:''}<button class="btn" data-start="${test.id}" ${disabled?'disabled':''}>Start Free Mock</button></div><p class="mt">${required?'Membership is checked before every attempt. Successful verification starts this mock automatically.':'No Telegram check is required for this mock.'}</p>${!connected?'<p class="muted">Supabase and Telegram configuration are pending. Test starts are unavailable in this preview.</p>':''}</section>`;
  }

  function auth(register,params){
    const next=destination(params),s=access.snapshot,disabled=!connected||s.busy;
    return `<section class="card auth-mvp">${title('STUDENT ACCOUNT',register?'Register':'Log in','Sign in before attempting any free or premium mock test.')}${statusMessage()}<form id="auth-form" data-mode="${register?'register':'login'}" data-next="${escape(next)}">${register?`<div class="field"><label for="full-name">Name</label><input id="full-name" name="displayName" autocomplete="name" required ${disabled?'disabled':''}></div>`:''}<div class="field"><label for="email">Email address</label><input id="email" name="email" type="email" autocomplete="username" required ${disabled?'disabled':''}></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="${register?'new-password':'current-password'}" required ${disabled?'disabled':''}></div><button class="btn wide" ${disabled?'disabled':''}>${register?'Register':'Log in'}${!connected?' · Backend required':''}</button></form><p class="mt">${register?'Already registered?':'New to Sahoo ExamNexa?'}</p>${authLink(register?'login':'register',next,register?'Log in':'Register')}<p class="mt">A persistent signed-in session will be restored through the authentication service. Credentials are sent to Supabase Auth when configured. No local account is created.</p></section>`;
  }
  function account(){const s=access.snapshot;return title('STUDENT ACCOUNT','My account','Your profile, subject access and saved attempts.')+statusMessage()+`<section class="card auth-mvp"><h2>${s.status==='authenticated'?'Signed-in student':'Not signed in'}</h2>${s.user?`<p>${escape(s.user.displayName)}</p><p>${escape(s.user.email)}</p>`:'<p>Log in to see your account. No student records are simulated.</p><div class="chips">'+link('login','Log in','btn')+link('register','Register','btn secondary')+'</div>'}<div class="chips mt">${link('orders','My subjects & orders','btn secondary')}<button class="btn secondary" data-logout ${!connected||s.status!=='authenticated'?'disabled':''}>Log out</button></div><p class="mt">Logging out clears the local attempt and account view. Configured Supabase sessions are revoked and results are saved server-side.</p></section>`;}
  function premiumStatus(record=null){return `<div class="notice"><strong>${escape(subjectAccessLabel(record))}</strong><p>Premium attempts require login and active subject access. The server rechecks expiry before every attempt.</p>${record?.state==='payment_pending'?'<p>Your UTR is awaiting Admin verification. Submission alone does not unlock access.</p>':''}${record?.state==='expired'?link('subjects','Renew access','text-link'):''}</div>`;}
  function stateGuide(){return '<details class="mt"><summary>Subject access states · Interface guide</summary><div class="details-body"><p>These are state labels, not account records.</p><div class="grid cols-2">'+[['Locked','Buy subject access to begin.'],['Payment pending','Admin must confirm the received payment.'],['Active until [expiry date]','The server supplies the expiry date; initial validity is three calendar months.'],['Expired','Premium tests lock when access expires.'],['Renew access','Buy a renewal and submit its UTR for manual approval.']].map(([h,p])=>`<div><h3>${h}</h3><p>${p}</p></div>`).join('')+'</div></div></details>';}
  function adminSettings(){const p=access.snapshot.policy;return `<section class="card"><h2>Launch access settings</h2><p>Admin-controlled settings stored on the future backend. This public preview cannot save or grant access.</p><div class="form-grid"><div class="field"><label for="launch-telegram">Telegram requirement</label><select id="launch-telegram" disabled><option>${p.telegramRequired?'ON':'OFF'} · Preview policy</option><option>${p.telegramRequired?'OFF':'ON'}</option></select></div>${[['launch-youtube-url','YouTube channel URL (voluntary promotion)','url'],['launch-telegram-url','Telegram channel link','url'],['launch-price','Subject price (INR)','number']].map(([id,l,t])=>`<div class="field"><label for="${id}">${l}</label><input id="${id}" type="${t}" disabled placeholder="Set by authorized Admin"></div>`).join('')}<div class="field"><label for="launch-validity">Subject validity (calendar months)</label><input id="launch-validity" type="number" min="1" value="3" disabled></div><div class="field"><label for="launch-test-access">Test access type</label><select id="launch-test-access" disabled><option>FREE</option><option>PREMIUM</option></select></div><div class="field"><label for="launch-publication">Test visibility</label><select id="launch-publication" disabled><option>Published</option><option>Hidden</option><option>Draft</option></select></div></div><button class="btn" disabled>Save launch settings · Backend required</button><p class="mt">Select the subject or test in its existing Admin section. Price and validity changes apply to new orders; existing purchases retain their accepted terms.</p><p>Telegram membership is checked before each free attempt. YouTube subscriptions and bell-notification status are never verified.</p><p class="notice">YouTube promotion is always voluntary. Its channel URL can be edited; there is no subscription requirement switch.</p></section>`;}
  return {youtubePromotion,freeGate,auth,account,premiumStatus,stateGuide,adminSettings,destination};
}
