import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {PGlite} from '@electric-sql/pglite';
import {makeHandler,makeWebhook} from '../supabase/functions/_shared/handler.mjs';
import {inspectCanonicalHtml} from '../scripts/html-import.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true}),db=new PGlite();
const base='http://127.0.0.1:4173',project='https://fixture.supabase.co',student='10000000-0000-4000-8000-000000000001',admin='10000000-0000-4000-8000-000000000003';
const checks=[],errors=[];let member=true,outage=false,activeResponse;
const context=await browser.newContext({viewport:{width:1280,height:1000}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
const go=async path=>{await page.goto(base+'/#/'+path);await page.locator('#main').waitFor();};
const rpc=async(actor,action,payload={})=>(await db.query('select public.academy_api($1,$2,$3) as result',[actor,action,JSON.stringify(payload)])).rows[0].result;
const q={id:'q1',number:1,text:'Synthetic fixture question <img src=x onerror=alert(1)> 🟢',topic:'Fixture subject',options:['one','two','three','four'].map((text,i)=>({id:'o'+i,text})),correctOptionId:'o1',explanation:'Fixture explanation',tags:['SAMPLE ONLY']};
const html='<script type="application/json" id="sahoo-mock-data">'+JSON.stringify({questionCount:2,questions:[q,{...q,id:'q2',number:2,text:'Synthetic second question',correctOptionId:'o0'}]})+'</script>';
const user=id=>({id,aud:'authenticated',role:'authenticated',email:(id===admin?'admin':'student')+'@fixture.invalid',email_confirmed_at:'2026-10-01T00:00:00Z',created_at:'2026-10-01T00:00:00Z',app_metadata:{provider:'email'},user_metadata:{}});
const tokens=new Map();function session(id){const u=user(id),exp=Math.floor(Date.now()/1000)+3600;const b=o=>Buffer.from(JSON.stringify(o)).toString('base64url');const token=b({alg:'HS256',typ:'JWT'})+'.'+b({sub:id,aud:'authenticated',role:'authenticated',exp,iss:project+'/auth/v1'})+'.fixture-signature';tokens.set(token,u);return {access_token:token,token_type:'bearer',expires_in:3600,expires_at:exp,refresh_token:'fixture-'+id,user:u};}
try{
  await db.exec("create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated,anon;");
  for(const f of fs.readdirSync('supabase/migrations').sort())await db.exec(fs.readFileSync('supabase/migrations/'+f,'utf8'));
  await db.query("insert into auth.users(id) values($1),($2)",[student,admin]);await db.query("update public.profiles set role='admin' where id=$1",[admin]);
  const save=(entity,record)=>rpc(admin,'adminSave',{entity,record});
  await save('exams',{id:'exam',name:'Fixture exam',published:true});await save('subjects',{id:'subject',name:'Fixture subject',exam_ids:['exam'],price_paise:9900,validity_months:3,published:true});await save('topics',{id:'topic',subject_id:'subject',name:'Fixture topic',published:true});
  await save('admin_settings',{telegram_required:true,telegram_chat_id:'-100100',telegram_url:'https://t.me/fixture',youtube_url:'https://www.youtube.com/@fixture',upi_id:'fixture@upi',payee_name:'Fixture payee',qr_url:project+'/storage/v1/object/public/payment-assets/qr.svg'});
  for(const id of ['free','paid']){const rec={id,subject_id:'subject',topic_id:'topic',title:'Fixture '+id+' test',access:id,duration_seconds:600,published:false};await save('tests',rec);await rpc(admin,'adminImport',{testId:id,html,import:inspectCanonicalHtml(html)});const imp=(await db.query('select id from public.imports where test_id=$1',[id])).rows[0];await rpc(admin,'adminVerifyContent',{importId:imp.id,decision:'approve',reason:'Synthetic fixture fully reviewed for this isolated test.'});await save('tests',{...rec,published:true});}
  const cfg={origins:[base],botToken:'123:fixture',chatId:'-100100',botUsername:'fixture_bot',webhookSecret:'fixture-secret'};
  const handler=makeHandler({rpc,getUser:async token=>tokens.get(token),config:cfg,inspectHtml:inspectCanonicalHtml,fetcher:async(url,init)=>{if(outage)throw new Error('Fixture outage');return Response.json({ok:true,result:{status:JSON.parse(init.body).user_id===123?'administrator':member?'member':'left'}});}});
  const webhook=makeWebhook({rpc,secret:cfg.webhookSecret});
  await context.route(base+'/**',async r=>{const u=new URL(r.request().url());if(u.pathname==='/public-config.json')return r.fulfill({json:{url:project,publishableKey:'sb_publishable_fixture'}});const response=await r.fetch();const headers={...response.headers()};if(headers['content-security-policy'])headers['content-security-policy']=headers['content-security-policy'].replace("connect-src 'self'","connect-src 'self' "+project).replace("img-src 'self'","img-src 'self' "+project);await r.fulfill({response,headers});});
  await context.route(project+'/**',async r=>{const req=r.request(),u=new URL(req.url()),cors={'access-control-allow-origin':base,'access-control-allow-headers':'authorization,apikey,content-type,x-client-info,x-supabase-api-version','access-control-allow-methods':'GET,POST,OPTIONS'};
    if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:cors});
    if(u.pathname.includes('/storage/'))return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="220" height="220"><rect width="220" height="220" fill="#ddd"/><text y="100" x="20">TEST QR ONLY</text></svg>',headers:cors});
    if(u.pathname==='/auth/v1/token'){const data=req.postDataJSON();return r.fulfill({json:session(data.email?.startsWith('admin')?admin:student),headers:cors});}
    if(u.pathname==='/auth/v1/user')return r.fulfill({json:tokens.get(req.headers().authorization?.replace('Bearer ','')),headers:cors});
    if(u.pathname==='/auth/v1/logout')return r.fulfill({status:204,headers:cors});
    if(u.pathname==='/auth/v1/signup')return r.fulfill({json:{user:user(student),session:null},headers:cors});
    if(u.pathname==='/functions/v1/academy-api'){const response=await handler(new Request(req.url(),{method:req.method(),headers:req.headers(),body:req.postData()}));const body=await response.text();if(req.postDataJSON().action==='start')activeResponse=JSON.parse(body);return r.fulfill({status:response.status,headers:{...cors,...Object.fromEntries(response.headers)},body});}
    throw new Error('Unexpected fixture endpoint '+u.pathname);
  });
  const login=async name=>{await go('login');await page.locator('#email').fill(name+'@fixture.invalid');await page.locator('#password').fill('fixture-password-only');await page.locator('#auth-form button').click();await page.getByRole('heading',{name:'Signed-in student'}).waitFor();};
  const logout=async()=>{await page.locator('.top-actions [data-logout]').click();await page.waitForURL('**/#/account');await page.getByRole('heading',{name:'Not signed in'}).waitFor();};
  assert.equal((await page.goto(base+'/admin')).status(),404);await go('admin');await page.getByRole('heading',{name:'Admin sign-in required'}).waitFor();assert.equal(await page.locator('a[href^="#/admin"]').count(),0);checks.push('Direct /admin is not served; SPA Admin denies visitors and has no public navigation');
  await go('admin');await page.getByRole('heading',{name:'Admin sign-in required'}).waitFor();assert.equal(await page.locator('main form').count(),0);checks.push('Anonymous Admin routes expose no records or controls');
  await go('register');await page.locator('#full-name').fill('New student');await page.locator('#email').fill('new@fixture.invalid');await page.locator('#password').fill('fixture-password-only');await page.locator('#auth-form button').click();await page.getByText('Check your email to confirm registration, then log in.',{exact:true}).waitFor();checks.push('Registration stays unverified until email confirmation; no local account is invented');await login('student');await page.reload();await page.getByRole('heading',{name:'Signed-in student'}).waitFor();await go('admin');await page.getByRole('heading',{name:'Admin sign-in required'}).waitFor();assert.equal(await page.locator('a[href^=\"#/admin\" ]').count(),0);checks.push('Official SDK login/session restoration works against isolated Auth transport; student Admin view denied');
  await go('home');await page.getByRole('heading',{name:'Topic-wise Mock Tests',exact:true}).waitFor();await page.getByRole('link',{name:'Choose exam'}).click();await page.getByRole('link',{name:'Explore topics'}).click();await page.getByRole('link',{name:'View tests'}).click();assert.equal(await page.getByRole('link',{name:'View test',exact:true}).count(),2);checks.push('Database catalog keeps Exam → Subject → Topic → Free/Premium journey');
  await go('test/free');await page.getByRole('button',{name:'Connect Telegram'}).click();const url=await page.getByRole('link',{name:'Open Telegram bot'}).getAttribute('href');await webhook(new Request('https://webhook.invalid',{method:'POST',headers:{'x-telegram-bot-api-secret-token':cfg.webhookSecret},body:JSON.stringify({message:{chat:{id:456,type:'private'},from:{id:456},text:'/start '+new URL(url).searchParams.get('start')}})}));await page.getByRole('button',{name:'Return to test'}).click();
  member=false;await page.getByRole('button',{name:'Verify Membership',exact:true}).click();await page.getByText('Not verified — Join Sahoo ExamNexa Telegram',{exact:true}).waitFor();assert.equal(await page.locator('#timer').count(),0);outage=true;await page.getByRole('button',{name:'Verify Again',exact:true}).click();await page.getByText('Telegram verification temporarily unavailable. Please retry.',{exact:true}).waitFor();outage=false;member=true;await page.getByRole('button',{name:'Verify Again',exact:true}).click();await page.locator('#timer').waitFor();assert.ok(!JSON.stringify(activeResponse).includes('correctOptionId'));assert.equal(await page.locator('.question-text img').count(),0);checks.push('Telegram nonce binding and every-start membership failure/retry use real handler and SQL; protected response omits keys');
  await page.locator('input[name=answer][value="1"]').check();await page.getByRole('button',{name:'Mark for Review',exact:true}).click();await page.getByRole('button',{name:'Save & Next'}).click();await page.locator('input[name=answer][value="0"]').check();await page.getByRole('button',{name:'Finish & review'}).click();await page.getByRole('button',{name:'Submit sample'}).click();await page.waitForURL('**/#/results');await page.locator('.score-ring b').waitFor();assert.equal(await page.locator('.score-ring b').innerText(),'2/2');await page.reload();await page.getByRole('button',{name:'Review result'}).click();await page.locator('.score-ring b').waitFor();assert.equal(await page.locator('.review-item').count(),2);checks.push('Existing CBT flags/navigation and server answer saves/scoring/review survive reload; HTML text is escaped');
  await go('purchase/subject');await page.getByRole('button',{name:'Create / view payment order'}).click();await page.locator('#live-utr').fill('FIXTUREUTR123');await page.getByRole('button',{name:'Submit UTR for Admin verification'}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();await go('test/paid');await page.getByText('Payment pending',{exact:true}).waitFor();assert.ok(await page.getByRole('button',{name:'Start Premium Mock'}).isDisabled());checks.push('Server-priced UPI order and UTR submission stay pending; premium start remains disabled');
  await logout();await login('admin');await go('admin/payments');await page.locator('textarea[name=reason]').fill('Fixture exact received credit checked against UPI bank record');await page.locator('select[name=decision]').selectOption('approve');await page.locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Save decision'}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();assert.equal((await rpc(student,'access',{subjectId:'subject'})).state,'active');checks.push('Private Admin manual receipt approval atomically activates the subject');
  await go('admin/tests');await page.locator('#live-id').fill('import-fixture');await page.locator('#live-title').fill('Import fixture');await page.locator('#live-subject_id').fill('subject');await page.locator('#live-topic_id').fill('topic');await page.getByRole('button',{name:'Save to database'}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();await go('admin/imports');await page.locator('#live-testId').fill('import-fixture');await page.locator('#live-expectedCount').fill('2');await page.locator('input[type=file]').setInputFiles({name:'fixture.html',mimeType:'text/html',buffer:Buffer.from(html)});await page.getByRole('button',{name:'Import and run structural pass'}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();assert.equal((await db.query("select imported_count from public.imports where test_id='import-fixture'")).rows[0].imported_count,2);assert.equal((await db.query("select published from public.tests where id='import-fixture'")).rows[0].published,false);checks.push('Private single-HTML upload stores exact count and source; content pass stays pending and test hidden');
  for(const width of [375,768,1280]){await page.setViewportSize({width,height:900});for(const r of ['admin/payments','admin/subjects','admin/imports','purchase/subject','test/free','account']){await go(r);await page.waitForTimeout(120);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width+' '+r);}}
  checks.push('Connected student/Admin routes fit phone, tablet and laptop widths');
  assert.equal(await page.locator('.sidebar a[href="#/admin"]').count(),1);
  await go('admin/settings');await page.locator('#live-youtube_name').fill('Sahoo ExamNexa Study');await page.locator('#live-youtube_cta').fill('Subscribe on YouTube');await page.locator('#live-youtube_videos_url').fill('https://www.youtube.com/playlist?list=fixture');await page.locator('#live-telegram_scope').selectOption('selected');await page.locator('#live-telegram_required').selectOption('false');await page.getByRole('button',{name:'Save to database'}).click();await page.getByText('Saved successfully.',{exact:true}).waitFor();
  const savedPolicy=await rpc(null,'policy');assert.equal(savedPolicy.telegramRequired,false);assert.equal(savedPolicy.telegramScope,'selected');assert.equal(savedPolicy.youtubeChannelName,'Sahoo ExamNexa Study');
  await go('home');await page.locator('main .youtube-promotion').waitFor();assert.equal(await page.locator('main .youtube-promotion a').filter({hasText:'Watch Free Study Videos'}).getAttribute('href'),'https://www.youtube.com/playlist?list=fixture');checks.push('Admin-only settings persist promotion and Telegram switches; public promotion updates without a rebuild');
  await page.setViewportSize({width:1280,height:1000});await go('admin/tests');await page.screenshot({path:'test-artifacts/backend-admin-fixture.png',fullPage:true});
  await logout();await login('student');member=false;outage=true;await go('test/paid');await page.getByRole('button',{name:'Start Premium Mock'}).waitFor();await page.waitForFunction(()=>!document.querySelector('[data-start]')?.disabled);await page.getByRole('button',{name:'Start Premium Mock'}).click();await page.locator('#timer').waitFor();await page.getByRole('button',{name:'Finish & review'}).click();await page.getByRole('button',{name:'Submit sample'}).click();await page.waitForURL('**/#/results');checks.push('Approved student can start protected premium CBT with server-only questions');
  await page.locator('.top-actions [data-logout]').click();await page.waitForURL('**/#/account');await page.reload();await page.getByRole('heading',{name:'Not signed in'}).waitFor();checks.push('SDK logout clears persistent session and private result view');assert.deepEqual(errors,[]);fs.writeFileSync('test-artifacts/supabase-browser-results.json',JSON.stringify({passed:checks.length,checks,errors,transport:'Isolated Auth and Telegram transport, official SDK, actual handler and PostgreSQL migrations; not a live Supabase connection'},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors},null,2));
}finally{await context.unrouteAll({behavior:'wait'});await context.close();await browser.close();await db.close();}
