import test from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler,makeWebhook,checkTelegram,isMember,sha256} from '../supabase/functions/_shared/handler.mjs';
import {validPublicConfig,createSupabaseGateway} from '../supabase-gateway.js';
const config={origins:['http://127.0.0.1:4173'],botToken:'123:fixture-only',chatId:'-100100',botUsername:'fixture_bot',webhookSecret:'fixture-secret'};
const request=(action,payload={},token='valid')=>new Request('https://fixture.invalid',{method:'POST',headers:{origin:config.origins[0],'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify({action,payload})});
function setup(overrides={}){const calls=[];const rpc=async(actor,action,payload)=>{calls.push({actor,action,payload});return action==='account'?{role:'student'}:action==='gateContext'?{required:true,channelId:config.chatId,policyVersion:1}:action==='policy'?{version:1,telegramRequired:true}:action==='catalog'?{tests:[{id:'free',access:'free'}]}:action==='telegramState'?{telegram_id:234}:action==='start'?{status:'started'}:{status:'eligible'};};return {calls,handler:makeHandler({rpc,getUser:async token=>token==='valid'?{id:'student',email_confirmed_at:'2026-10-01'}:null,config,fetcher:async()=>Response.json({ok:true,result:{status:'administrator'}}),...overrides})};}
test('public config accepts only publishable key and hosted HTTPS URL',()=>{assert.ok(validPublicConfig({url:'https://fixture.supabase.co',publishableKey:'sb_publishable_fixture'}));for(const key of ['sb_secret_fixture','eyJlegacyJWT','service-role',''])assert.equal(validPublicConfig({url:'https://fixture.supabase.co',publishableKey:key}),false);assert.equal(validPublicConfig({url:'https://evil.example',publishableKey:'sb_publishable_fixture'}),false);});
test('protected calls require server-validated confirmed email; invalid tokens never downgrade',async()=>{const {handler,calls}=setup();for(const token of [null,'invalid'])assert.equal((await handler(request('orders',{},token))).status,401);assert.equal(calls.length,0);assert.equal((await handler(request('catalog',{},null))).status,200);assert.equal((await handler(request('catalog',{},'invalid'))).status,401);const unconfirmed=setup({getUser:async()=>({id:'x'})});assert.equal((await unconfirmed.handler(request('orders'))).status,401);});
test('student Admin and internal RPC actions are denied',async()=>{const {handler,calls}=setup();assert.equal((await handler(request('adminSave',{actor:'admin',role:'admin'}))).status,403);for(const action of ['telegramConsume','telegramBegin','rateLimit','adminImport'])assert.equal((await handler(request(action))).status,400);assert.ok(calls.every(c=>c.action==='account'));});
test('origin and HTTP verb checks apply',async()=>{const {handler}=setup();assert.equal((await handler(new Request('https://fixture.invalid',{headers:{origin:'https://evil.example'}}))).status,403);assert.equal((await handler(new Request('https://fixture.invalid'))).status,405);});
test('oversized input is rejected before invoking a database operation',async()=>{const {handler,calls}=setup();const result=await handler(new Request('https://fixture.invalid',{method:'POST',headers:{'content-length':'3000000'},body:'{}'}));assert.equal(result.status,413);assert.equal(calls.length,0);});
test('every free start calls Telegram anew and ignores caller verification/identity',async()=>{let calls=0;const {handler,calls:rpcCalls}=setup({fetcher:async()=>{calls++;return Response.json({ok:true,result:{status:calls<=2?'administrator':'left'}});}});const p={testId:'free',idempotencyKey:crypto.randomUUID(),telegramVerified:true,actor:'admin',policyVersion:999};const a=await(await handler(request('start',p))).json();assert.equal(a.status,'started');const b=await(await handler(request('start',p))).json();assert.equal(b.status,'denied');const start=rpcCalls.find(c=>c.action==='start');assert.equal(start.actor,'student');assert.equal(start.payload.policyVersion,1);assert.equal('actor' in start.payload,false);});
test('Telegram outages/non-admin bot fail closed; restricted members require is_member',async()=>{assert.equal(isMember({status:'restricted',is_member:false}),false);assert.equal(isMember({status:'restricted',is_member:true}),true);for(const fetcher of [async()=>{throw new Error('token-secret must not leak');},async()=>Response.json({ok:true,result:{status:'member'}})])assert.equal((await checkTelegram({token:config.botToken,chatId:config.chatId,userId:234,fetcher})).verified,false);});
test('Telegram link stores only a hash, never accepts a browser telegram ID',async()=>{const {handler,calls}=setup();const result=await(await handler(request('beginSocialLink',{telegramId:999}))).json();const nonce=new URL(result.authorizationUrl).searchParams.get('start');assert.match(nonce,/^[a-f0-9]{48}$/);const stored=calls.find(c=>c.action==='telegramBegin');assert.equal(stored.payload.nonceHash,await sha256(nonce));assert.equal('telegramId' in stored.payload,false);});
test('webhook requires secret and binds only a private sender through an unused nonce',async()=>{const calls=[];const handler=makeWebhook({secret:'fixture',rpc:async(...args)=>{calls.push(args);return {linked:true};}});const body={message:{chat:{id:123,type:'private'},from:{id:123,is_bot:false},text:'/start '+'a'.repeat(48)}};const req=secret=>new Request('https://fixture.invalid',{method:'POST',headers:{'x-telegram-bot-api-secret-token':secret},body:JSON.stringify(body)});assert.equal((await handler(req('wrong'))).status,403);assert.equal(calls.length,0);assert.equal((await handler(req('fixture'))).status,200);assert.equal(calls[0][2].telegramId,'123');assert.equal(calls[0][2].nonceHash,await sha256('a'.repeat(48)));});
test('SDK gateway uses real Auth methods and confirmed remote user, not local role metadata',async()=>{const calls=[];const client={auth:{getSession:async()=>({data:{session:null}}),signUp:async c=>{calls.push(c);return {data:{session:null}};},signOut:async()=>({error:null})}};const g=createSupabaseGateway(client,{});assert.deepEqual(await g.getSession(),{status:'anonymous'});await g.logout();assert.equal(g.realBackend,true);});
test('unlinked students cannot self-assert Telegram identity or membership',async()=>{
  let starts=0;const {handler}=setup({rpc:async(actor,action)=>{if(action==='catalog')return {tests:[{id:'free',access:'free'}]};if(action==='gateContext')return {required:true,channelId:'-100100',policyVersion:2};if(action==='telegramState')return {};if(action==='start')starts++;return {};},fetcher:async()=>{throw Error('Should not call Telegram without a linked ID');}});
  const r=await(await handler(request('start',{testId:'free',telegram_id:1,member:true,telegramVerified:true}))).json();assert.equal(r.status,'denied');assert.equal(r.freeAccess.checks[0].status,'not_linked');assert.equal(starts,0);
});
test('paid and exempt free mocks make no Telegram requests during outages',async()=>{
  for(const access of ['paid','free']){const seen=[];const {handler}=setup({rpc:async(actor,action,payload)=>{seen.push(action);if(action==='catalog')return {tests:[{id:'test',access}]};if(action==='gateContext')return {required:false,channelId:null,policyVersion:3};if(action==='start')return {status:'started'};return {};},fetcher:async()=>{throw Error('Must not call Telegram');}});
    assert.equal((await(await handler(request('start',{testId:'test',idempotencyKey:crypto.randomUUID()}))).json()).status,'started');assert.ok(!seen.includes('telegramState'));assert.ok(!seen.includes('telegramRecord'));
  }
});
test('Telegram timeout is an explicit retry state and never starts a mock',async()=>{
  const {handler,calls}=setup({fetcher:async()=>{throw Error('fixture timeout');}});const r=await(await handler(request('start',{testId:'free'}))).json();assert.equal(r.status,'denied');assert.equal(r.freeAccess.status,'verification_unavailable');assert.ok(!calls.some(c=>c.action==='start'));
});
